export const TOKEN_NAMES: { [key: string]: string } = {
    SBERRUB: 'Сбербанк',
    TCSBRUB: 'Тинькофф',
    OPNBRUB: 'Открытие',
    GPBRUB: 'Газпромбанк',
    HCBRUB: 'Хоум кредит',
    ACRUB: 'Альфабанк',
    ROSBRUB: 'РосБанк',
    RFBRUB: 'Райффайзен',
    MTSBRUB: 'МТС банк',
    POSTBRUB: 'Почта банк',
    RUSSTRUB: 'Русский Стандарт',
    TBRUB: 'ВТБ',
    RSHBRUB: 'Россельхозбанк',
    PHONERUB: 'Пополнение телефона',
    CASHRUB: 'Наличные RUB',
    QWRUB: 'QIWI',
    SBPRUB: 'СБП',
    SOVKRUB: 'Совкомбанк',
    YMRUB: 'Юмани',
    MKBRUB: 'МКБ',
    INTERBRUB: 'Межбанк',
    USDTTRC: 'USDT',
    TRNTBRUBSBP: 'ТрансСбп',
    ETH: 'ETH',
    USDTETH: 'USDTETH',
    USDTBSC: 'USDTBSC',
    BTC: 'BTC',
};
